apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
- app.yaml
- ingress.yaml
images:
- name: ghcr.io/rparmer/podinfo-image-automation
  newTag: v1.0.1 # {"$imagepolicy": "staging:podinfo-image-automation:tag"}
