apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - app.yaml
images:
  - name: ghcr.io/rparmer/podinfo-image-automation
    newTag: v1.0.0 # {"$imagepolicy": "staging:podinfo-image-automation:tag"}
