---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: podinfo-image-automation
  namespace: flux-system
spec:
  interval: 1m
  image: ghcr.io/rparmer/podinfo-image-automation
  accessFrom:
    namespaceSelectors:
      - matchLabels: {} # allow all namespaces
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: podinfo-image-automation
  namespace: dev
spec:
  imageRepositoryRef:
    name: podinfo-image-automation
    namespace: flux-system
  filterTags:
    pattern: '^main-(?P<ts>.*)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: podinfo-image-automation
  namespace: dev
spec:
  sourceRef:
    kind: GitRepository
    name: podinfo-image-automation
    namespace: flux-system
  interval: 1m
  update:
    path: ./dev
    strategy: Setters
  git:
    checkout:
      ref:
        branch: release
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@users.noreply.github.com
      messageTemplate: |
        [ci skip] An automated update from FluxBot
    push:
      branch: release
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: podinfo-image-automation
  namespace: staging
spec:
  imageRepositoryRef:
    name: podinfo-image-automation
    namespace: flux-system
  filterTags:
    pattern: '^v(?P<version>.*)'
    extract: '$version'
  policy:
    semver:
      range: '>=1.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: podinfo-image-automation
  namespace: staging
spec:
  sourceRef:
    kind: GitRepository
    name: podinfo-image-automation
    namespace: flux-system
  interval: 1m
  update:
    path: ./staging
    strategy: Setters
  git:
    checkout:
      ref:
        branch: release
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@users.noreply.github.com
      messageTemplate: |
        [ci skip] An automated update from FluxBot
    push:
      branch: release
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: podinfo-image-automation
  namespace: prod
spec:
  imageRepositoryRef:
    name: podinfo-image-automation
    namespace: flux-system
  filterTags:
    pattern: '^v(?P<version>.*)'
    extract: '$version'
  policy:
    semver:
      range: '>=1.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: podinfo-image-automation
  namespace: prod
spec:
  sourceRef:
    kind: GitRepository
    name: podinfo-image-automation
    namespace: flux-system
  interval: 1m
  update:
    path: ./prod
    strategy: Setters
  git:
    checkout:
      ref:
        branch: release
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@users.noreply.github.com
      messageTemplate: |
        [ci skip] An automated update from FluxBot
    push:
      branch: release
