apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - app.yaml
images:
  - name: ghcr.io/rparmer/podinfo-image-automation
    newName: ghcr.io/rparmer/podinfo-image-automation # {"$imagepolicy": "dev:podinfo-image-automation:name"}
    newTag: main-1656703597 # {"$imagepolicy": "dev:podinfo-image-automation:tag"}
