apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - app.yaml
configMapGenerator:
  - name: podinfo-image-automation
    envs:
      - image.env
images:
  - name: ghcr.io/rparmer/podinfo-image-automation
    newName: ghcr.io/rparmer/podinfo-image-automation # {"$imagepolicy": "dev:podinfo-image-automation:name"}
    newTag: main-1656704279 # {"$imagepolicy": "dev:podinfo-image-automation:tag"}
replacements:
  # - source:
  #     kind: ConfigMap
  #     name: podinfo-image-automation
  #     fieldPath: data.IMAGE_TAG
  #   targets:
  #     - select:
  #         kind: Deployment
  #         name: podinfo
  #       fieldPaths:
  #         - spec.template.spec.containers.[name=podinfod].image
  #       options:
  #         delimiter: ":"
  #         index: 1
  - source:
      kind: ConfigMap
      name: podinfo-image-automation
      fieldPath: data.IMAGE_TIMESTAMP
    targets:
      - select:
          kind: Deployment
          name: podinfo-image-automation
        fieldPaths:
          - spec.template.metadata.labels.[image.timestamp]
        options:
          create: true
patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
    target:
      kind: Deployment
      name: podinfo-image-automation
