apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
- app.yaml
- ingress.yaml
images:
- name: ghcr.io/rparmer/podinfo-image-automation
  newTag: main-1657052027 # {"$imagepolicy": "dev:podinfo-image-automation:tag"}
